# Generated by Django 2.1.3 on 2018-12-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20181209_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pay_passwd',
            field=models.CharField(max_length=50),
        ),
    ]
