# Generated by Django 2.1.3 on 2018-12-11 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20181209_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='regtime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
