# Generated by Django 2.1.3 on 2018-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_account_regtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='/avatar/48.jpg', upload_to='avatar'),
            preserve_default=False,
        ),
    ]
