# Generated by Django 2.1.3 on 2018-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20181211_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.CharField(max_length=266),
        ),
    ]
