# Generated by Django 2.1.3 on 2018-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_auto_20181216_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.CharField(max_length=300),
        ),
    ]
