# Generated by Django 2.1.3 on 2018-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_auto_20181221_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.FilePathField(null=True, path='C:\\Users\\omnitrix\\PycharmProjects\\virtualBank\\onlineBank\\authenticate\\rsa\\'),
        ),
    ]
