# Generated by Django 2.1.3 on 2018-12-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_auto_20181221_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('card', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('deal_identify', models.CharField(max_length=10)),
            ],
        ),
    ]
