# Generated by Django 2.1.3 on 2018-12-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_paybill_pay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybill',
            name='hash_pi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paybill',
            name='payer_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
